testutil/contract.go

Add memory for the dynamic params in the generated solidity test code.

Fix contract test for memory params

---

tracker/store/boltdb/bolt_store.go
tracker/store/inmem/inmem_store.go
tracker/store/postgresql/postgresql_store.go
tracker/store/store.go
tracker/store/testing.go
tracker/tracker.go

This PR changes the kv store to use string instead of []byte for keys and values because it is not easy to encode bytes in the Postgresql store.

Use string as kv in tracker store

---

abi/decode.go
contract/contract.go

This PR closes #58. An empty input and thus the panic happens when you call a function that is not part of the contract and the eth_call returns an empty []byte. There should be a safe check on contract so that it fails on an empty response before checking Decode. Besides, we include some safe checks on abi as well.

Fix empty response

---

etherscan/etherscan.go

This PR adds another field into the Etherscan API to retrieve the contract source code for a given address if exists.

Add Etherscan getContract api method

---

jsonrpc/eth.go
jsonrpc/eth_test.go
structs.go
testutil/server.go

There are some state endpoints (StorageAt, Balance, Code or TransactionCount) that be queried both at a block number or by block hash. Right now there is only support for block number (or block label like "latest" or "pending). This PR adds support to query those endpoints by block hash as well.

Add hash and block filter for state endpoints

---

abi/abi.go
abi/encoding_test.go
contract/contract.go

This PR adds helper methods to encode/decode smart contract calls inside the Method struct. Closes #108.

Add helper methods for encoding/decoding

---

jsonrpc/client.go
jsonrpc/transport/http.go
jsonrpc/transport/transport.go
jsonrpc/transport/websocket.go

This PR allows setting the `MaxConnsPerHost` in  jsonrpc http transport.

Added new method to set maxConns limit for jsonrpc transport

---

abi/abi.go
abi/abi_test.go
abi/encode.go
abi/encoding_test.go
go.sum

This PR fixes 2 newly found issues:
**Improvement**:
- When parsing JSON as `interface{}` in Go, all numbers are parsed as `float64`. Currently the library will fail to encode the params if a number is passed as `float64` so we cast into an `int64` before encoding it.
- We would like to pass addresses as strings such as "0x905B88EFf8Bda1543d4d6f4aA05afef143D27E18". Currently the library will fail if we pass a string when expecting an `address`.
**Bug fix**:
This library currently does not account for overloaded functions and events. In Solidity, polymorphism makes it such that multiple methods or events can have the same name but different parameters. Because of this, we must index the methods by appending an index to their name when multiple methods have the same name (same logic as used …

Best effort encoding + overload definitions

---

abi/type.go
abi/type_test.go

If 'int' and 'uint' types do not have bytes (i.e. int64) when parsing they default to int256 and uint256.

Decode bare uint and int as 256 bytes

---

abi/encode.go
abi/encoding_test.go

Currently, go-web3 does not support passing numbers as strings. Big numbers in Solidity that overflow the maximum Go size (such as uint256 and int256) need to be passed as Big Ints but the majority of users would actually prefer to pass these arguments as strings like it is done in `web3js` and `ethers.js`. 
This PR improves the best effort by trying to encode strings as numbers by transforming them into big.Int.

Encode strings to number as big.Int

---

abi/abi.go
abi/abi_test.go
contract/contract_test.go

This PR fixes the parsing of NewMethod as human readable ABI and makes it compatible with the one from [ethers.js](https://docs.ethers.io/v5/api/utils/abi/formats/#abi-formats--human-readable-abi). Closes #132.

Fix parse func types in NewMethod

---

jsonrpc/transport/websocket.go

Headers were added in #140, but not plumbed through to the websocket dialer.

Fix: jsonrpc: use header arg in websocket dialer for jsonrpc

---

structs.go
structs_marshal.go

According to the [Ethereum JSON-RPC spec](https://eth.wiki/json-rpc/API#eth_call), methods `estimateGas` and `call` can take in a transaction object.
The field `Gas` (gas limit) was missing from `CallMsg`. This PR adds that additional missing field

Add missing Gas field to CallMsg

---

structs.go
structs_marshal.go
structs_marshal_test.go
structs_unmarshal.go
tracker/tracker.go
tracker/tracker_test.go

Currently, the log filter does not support `Topics` [according to the spec](https://eth.wiki/json-rpc/API#eth_getlogs):
> topics: Array of DATA, - (optional) Array of 32 Bytes DATA topics. Topics are order-dependent. Each topic can also be an array of DATA with “or” options.
Notice the last sentence:
> Each topic can also be an array of DATA with “or” options.
This means that the `Topics` field of a log filter can accept an array of arrays, and not just a simple array.
A great example of usage is provided with [go-ethereum](https://pkg.go.dev/github.com/ethereum/go-ethereum#FilterQuery):
> 	// The Topic list restricts matches to particular event topics. Each event has a list
// of topics. Topics matches a prefix of that list. An empty element slice matches any
// topic. Non-empty elements …

Correct the topic field in log filters

---

README.md
ens/address_mapping.go
ens/ens.go
ens/ens_test.go
jsonrpc/client.go
networks.go

This PR adds a new wrapper module to resolve ENS domains. Before, go-web3 only had support to interact with the smart contract but the user had to supply the resolver address. Now, this new module introduces a more straightforward Api to do it, hard coding the default address for the default ENS resolver in the main networks.

Add ENS module

---

keystore/utils.go

Small fix to use lower case fields for the JSON file.

Use lower case fields in json file

---

CHANGELOG.md
structs.go
structs_test.go
testutil/util.go

This PR includes a `Copy() <T>` function for each of the major types (`Block`, `Transaction`, `Receipt` and `Log`).

Add copy functions for core types

---

jsonrpc/transport/websocket.go

This PR fixes the transport call of WebSocket.
The current version does not add the parameter JsonRPC. And because of that, the server returns an "invalid request" message, like the following
```
{
"jsonrpc": "2.0",
"error": {
"code": -32600,
"message": "Invalid request"
},
"id": 0
}
```
In order to fix that I've added the parameter on the codec request construction at the call method, similar to what is already practiced for the HTTP transport implementation.

fix websocket transport

---

structs_marshal_rlp.go

This is a critical DoS issue because multiple blockchain projects are using this to parse txn gossipped from other nodes or provided by users. Without this fixed, attackers can easily crash blockchain nodes.

[DoS] fix potential index out of range in txn unmarshalling

---

CHANGELOG.md
abi/decode.go
abi/decode_test.go

This PR fixes a possible out-of-bounds reading of the input bytes array during decoding.

Add bound check to abi encoder

---

jsonrpc/eth.go

See:
- Edge Issue https://github.com/0xPolygon/polygon-edge/issues/640
- Edge PR: https://github.com/0xPolygon/polygon-edge/pull/641
The `ethgo` code had a workaround in it, for an issue with the Polygon Edge JSON/RPC responses for `eth_getFilterChanges`. Specifically that they were returning a `string` rather than JSON Arrays in the `result`.
This PR updates `ethgo` to expect the standard outputs from these JSON/RPC functions, and hence depends on https://github.com/0xPolygon/polygon-edge/pull/641 to work with Polygon Edge.

Expect the correct JSON/RPC results from eth_getFilterChanges calls

---

CHANGELOG.md
abi/decode.go
abi/encoding_test.go

This PR includes a custom struct tag for `abi.DecodeStruct`.

Use custom tag for DecodeStruct

---

testutil/server.go
testutil/server_test.go

In the previous PR to fix `TestServer` the address was not set.

Fix `TestServer` deployment again

---

abi/abi.go
abi/abi_test.go
abi/type.go
abi/type_test.go

This PR adds the field `internalType` from the `abi` JSON file to the `abi.Type` object.

Add internal type to abi type

---

abi/abi_test.go
abi/decode.go
abi/decode_test.go
abi/encoding_test.go

This PR fixes a bug in which upon decoding a `length` for the array of bytes, the length of the rest of the data was not checked correctly. It also includes a fuzzing test that panics if the check is not done.

Bug decode abi bytes

---

CHANGELOG.md
jsonrpc/eth.go
jsonrpc/eth_test.go
structs.go
structs_marshal.go
structs_marshal_test.go

This PR expands the `eth_call` JSON-RPC call to add the override.

Add eth_call override

---

jsonrpc/transport/http.go

IPv6 endpoint addresses are currently not working by default, this enables IPv6 based endpoints.

Attempt to connect to both ipv4 and ipv6 addresses

---

blocktracker/blocktracker.go
tracker/tracker.go

The problem is when reorganization occurs on chain, so the parent block does not exist any more. function `handleReconcileImpl()` should check if the obtained block is `nil` (`parent == nil`):
`parent, err := t.provider.GetBlockByHash(block.ParentHash, false)`
There are some additional places in `blocktracker.go` and _tracker.go_ which should be handled also. They are introduces in this PR as well.

Fix tracker errors after a block reorganization

---

jsonrpc/transport/http.go

etho http component used by the block tracker does not handle status codes other than 200

Handle status codes other than 200 in jsonrpc/transport/http.go

---

structs_marshal.go

I believe we are hitting a memory leak in `fastjson` discussed here: https://github.com/valyala/fastjson/issues/24
This PR resets the `fastjson.ArenaPool` object after using it. It means we won't get cache hits across calls to `MarshalJSON` but given the cardinality of the data in blocks and transactions, I expect the impact to be minimal.
Happy to discuss if my assumption if incorrect.

Reset ArenaPool after use

---

structs.go
wallet/signer.go
wallet/signer_test.go

This PR simplifies transaction hash calculation a bit and uses the chain id provided by the hash function parameter, instead the one from the transaction object, since it can be empty.
Also, property-based tests include testing of dynamic fee transactions as well.

Fix hash calculation for dynamic fee and access list transactions

---

blocktracker/blocktracker.go
tracker/tracker.go

Use `BlockTracker` as a interface inside Tracker structure. That will allow anyone to use custom `BlockTracker` implementation.

abstract block tracker for tracker

---

jsonrpc/debug.go
jsonrpc/debug_test.go

According to the spec, `debug_traceTransaction` API endpoint accepts options which are not supported by ethgo now: https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debug_traceTransaction
This PR introduces options for the function that executes the given endpoint.

Added options to TraceTransaction function

---

etherscan/etherscan.go
etherscan/etherscan_test.go

Fix #258. You forgot to add apiKey in NewEtherscan. Also added a test to check it automatically for future modifications.

Fix #258 Etherscan created with corresponding apiKey

---

jsonrpc/transport/http.go

params is wrong:
```
{"jsonrpc":"2.0","id":0,"method":"eth_gasPrice","params":null}
```
With `[]` instead of `null` it does not happen.  
It happened with
```sh
npx hardhat node
```
It didn't happen when using 
``` sh
docker run --name geth-test -d -p 8545:8545 -p 8546:8546 ethereum/client-go:v1.10.15 --dev --datadir /eth1data --ipcpath /eth1data/geth.ipc --http --http.addr 0.0.0.0 --http.api eth,net,web3,debug --ws --ws.addr 0.0.0.0 --verbosity 4
```

fix "Code: -32600, Message: Invalid request" when using with hardhat
