- abi/abi.go
- abi/decode.go
- abi/encode.go
- abi/encoding_test.go
- abi/testing.go
- abi/type.go
- abi/type_test.go
> Tuples struct

- abi/abi.go
- abi/encode.go
- abi/encoding_test.go
- abi/testing.go
- abi/type.go
- abi/type_test.go
> Encode tuples in string format

- jsonrpc/transport/ipc.go
- jsonrpc/transport/transport.go
- jsonrpc/transport/websocket.go
> Add IPC transport

- abi/encoding_test.go
- compiler/compiler.go
- compiler/fixtures/auction.v.py
- compiler/fixtures/ballot.sol
- compiler/fixtures/crowdfund.v.py
- compiler/fixtures/simple_auction.sol
- compiler/solidity.go
- compiler/solidity_test.go
- compiler/vyper.go
- compiler/vyper_test.go
- scripts/circleci.sh
- testutil/server.go
This PR includes support for Vyper.
> Add Vyper compiler support

- abi/abi.go
- contract/contract.go
- go.mod
- go.sum
- jsonrpc/eth.go
- structs.go
- structs_marshal.go
- structs_unmarshal.go
- tracker/boltdb/bolt_store.go
- tracker/boltdb/bolt_store_test.go
- tracker/inmem_store.go
- tracker/store.go
- tracker/tracker.go
- tracker/tracker_test.go
This PR introduces an event tracker for smart contracts.
> Add tracker

- etherscan/etherscan.go
- etherscan/etherscan_test.go
- networks.go
- structs.go
- tracker/tracker.go
This PR adds an Etherscan provider and uses it to fasttrack the tracker. Closes #34
> Add etherscan provider and tracker fasttrack

- abi/abi.go
- abi/type.go
- jsonrpc/eth.go
- jsonrpc/eth_test.go
This PR adds the endpoint to get the current nonce and other utility functions.
> Add getNonce endpoint

- tracker/tracker.go
This PR adds a congestion control mechanism to the bulk sync. Infura returns error if the result for getLogs is bigger than 10k elements. In this scenario, tracker will use an additive increase multiplicative decrease algorithm (similar to TCP).
> Add congestion control to tracker

- jsonrpc/eth_test.go
- structs.go
- structs_unmarshal.go
> Decode transactions in block

- jsonrpc/transport/transport.go
> add check for secure websocket

- contract/contract.go
- jsonrpc/eth_test.go
- structs.go
- structs_encoding_test.go
- structs_marshal.go
- structs_unmarshal.go
- testutil/server.go
This PR adds the nonce in the transaction struct.
> Add nonce support

- jsonrpc/eth.go
- jsonrpc/eth_test.go
- testutil/contract.go
- testutil/server.go
Add the "eth_getStorageAt" endpoint.
> Add eth_getStorageAt endpoint

- jsonrpc/client.go
- jsonrpc/debug.go
- jsonrpc/debug_test.go
- testutil/server.go
Add the debug namespace and the "debug_traceTransaction" endpoint
> Add debug namespace

- abi/type.go
New function to create a new tuple type.
> Add function to create a new Tuple Type

- compiler/solidity.go
This PR adds some missing fields from the solidity compile output.
> Add missing fields in solidity compile

- abigen/gen.go
- abigen/main.go
- contract/builtin/ens/ens.go
- contract/builtin/ens/resolver.go
- contract/builtin/erc20/erc20.go
- contract/contract.go
This PR adds a new events signature function to the abigen.
> Add event signature to abigen

- README.md
I learned about this a while back, so when I saw this, perfect easy PR!
> Add golang highlighting to the examples!

- abi/abi.go
- abi/abi_test.go
> Fix parseMethodSignature without returns

- wallet/fixtures/wallet_json.json
- wallet/key.go
- wallet/wallet_json.go
- wallet/wallet_json_test.go
> Add json wallet support

- structs.go
- structs_test.go
- wallet/fixtures/wallet_json.json
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md
> Add EIP-55

- abi/abi.go
- abi/abi_test.go
- abi/testing.go
- abi/type.go
- abi/type_test.go
> Handle error types

- abi/revert.go
- abi/revert_test.go
This PR adds support to unpack require errors from the EVM execution.
> Add unpack for evm revert errors

- keystore/keystore.go
- keystore/keystore_test.go
- wallet/wallet_json.go
This PR completes support for the `keystore` format to encrypt and decrypt data.
> Add keystore encrypt/decrypt module

- structs.go
- structs_unmarshal.go
> Add status to receipt

- website/theme.config.js
A couple of fixes on the website.
> Fix website refs

- website/pages/_app.js
This PR adds plausible analytics collector.
> Add plausible web tracker

- CHANGELOG.md
- abi/topics.go
- abi/topics_test.go
> Decode fixed bytes in topic

- CHANGELOG.md
- contract/contract.go
- contract/contract_test.go
- wallet/signer.go
- wallet/signer_test.go
> Add nonce when sending transaction in contract

- .github/workflows/pr.yaml
- CHANGELOG.md
- contract/contract.go
- contract/contract_test.go
> Use block input in Call

- CHANGELOG.md
- structs.go
- testcases/transaction_test.go
- wallet/signer.go
This PR fixes the signing of typed transactions (i.e. EIP1559) and adds test coverage for it from `testcases`.
> Fix signature of typed transactions

- CHANGELOG.md
- contract/contract.go
- contract/contract_test.go
- structs_unmarshal.go
- testsuite/transaction-eip1159.json
- website/components/eip.jsx
- website/pages/contract.mdx
This PR adds initial support for EIP-1559.
> Add eip-1559

- builtin/ens/ens_resolver.go
- ens/ens.go
- ens/ens_test.go
> ENS supports reverse resolve

- CHANGELOG.md
- abi/abi.go
- abi/abi_test.go
- abi/encoding_test.go
This PR adds support to define a function with a multi-line string.
> Parse multiline abi function

- structs.go
- structs_test.go
> Fix copy method

- .github/workflows/pr.yaml
- abi/encoding_test.go
- abi/topics_test.go
- blocktracker/blocktracker_test.go
- contract/contract_test.go
- e2e/transaction_test.go
- jsonrpc/debug_test.go
- jsonrpc/eth_test.go
- jsonrpc/net_test.go
- jsonrpc/subscribe_test.go
- jsonrpc/transport/websocket.go
- jsonrpc/web3_test.go
- scripts/setup-geth.sh
- testcases/contract_test.go
- testcases/transaction_test.go
- testutil/server.go
- tracker/tracker_test.go
This PR moves the test server creation outside the unit tests.
> Move test server outside tests

- testutil/server.go
- testutil/server_test.go
This PR fixes an error in the deployment of the `Testutil` server.
> Fix deployment of testutil server

- structs.go
- structs_marshal.go
- structs_unmarshal.go
This PR adds baseFee in block structure for London fork Blocks.
> Add BaseFee field in block structure
